# Generated by Django 2.2 on 2019-09-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(to='eventFinderApp.Category'),
        ),
    ]
