# Generated by Django 2.2 on 2019-09-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0002_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='events', to='eventFinderApp.Category'),
        ),
    ]
