branch-defaults:
  dev:
    environment: null
    group_suffix: null
global:
  application_name: Free-Jubilee
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application
